language: php
php:
  - '5.5.9'
script:
  - composer install
  - zip -r release.zip . -x \*.git\*
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
